name: Actualisation Automatique Veille

on:
  schedule:
    - cron: '0 8 * * 1' # Tous les lundis à 08h00 UTC
  workflow_dispatch: # Permet de cliquer sur "Run workflow" dans GitHub pour tester immédiatement

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer feedparser
        run: pip install feedparser

      - name: Exécuter la mise à jour
        run: python update_veille.py

      - name: Commit et Push des modifications
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add veille.html
          git commit -m "Mise à jour automatique de la veille" || exit 0
          git push
